name: ESP32-S3-MINI CI Build

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install --upgrade setuptools

    - name: Run PlatformIO test build
      run:
        pio test -e hand_test -vv -f "*" --without-uploading --without-testing

    - name: Static code analysis
      run: pio check -e hand_firmware
    
    ## enable this after hand_main firmware done
    # - name: Run PlatformIO build
    #   run: pio run -e hand_firmware
